create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint not null,
  quantity integer not null default 1,
  created_at timestamptz not null default now(),
  constraint cart_items_user_product_unique unique (user_id, product_id)
);

alter table public.cart_items enable row level security;

create policy if not exists "Users can view own cart items"
  on public.cart_items
  for select
  using (auth.uid() = user_id);

create policy if not exists "Users can insert own cart items"
  on public.cart_items
  for insert
  with check (auth.uid() = user_id);

create policy if not exists "Users can update own cart items"
  on public.cart_items
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy if not exists "Users can delete own cart items"
  on public.cart_items
  for delete
  using (auth.uid() = user_id);

alter table public.cart_items
  add constraint cart_items_product_fkey
  foreign key (product_id) references public.products(id) on delete cascade;
