-- Stores the deterministic, rule-based "Stil Asistanı" report per user
-- (generated by app/api/style-assistant/route.ts). Run once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists style_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  report_text text not null,
  weekly_calendar jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now()
);

alter table style_reports enable row level security;

create policy "select_own_style_report" on style_reports
  for select using (auth.uid() = user_id);

create policy "insert_own_style_report" on style_reports
  for insert with check (auth.uid() = user_id);

create policy "update_own_style_report" on style_reports
  for update using (auth.uid() = user_id);
